# Generated by Django 4.0.4 on 2023-04-18 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('medicine_name', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_id', models.IntegerField()),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField(default=datetime.date(2024, 4, 17))),
            ],
        ),
    ]
